apiVersion: v1
data:
  DB_CONNECTION: pgsql
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: admin
  TGRES_USER: postgres
  spring.datasource.password: admin
  spring.datasource.url: jdbc:postgresql://db:5432/postgres
  spring.datasource.username: postgres
  spring.jpa.hibernate.ddl-auto: update
  spring.jpa.hibernate.show-sql: "true"
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-database-env
  name: db-database-env
